server:
  port: 8888

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://localhost:3306/software1?useSSL=false&characterEncoding=utf8
    username: root
    password: fjw258700
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.qingyuanbackend.model
mybatis-plus:






springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Logger Config
logging:
  level:
    com.hexadecimal: debug

jwt:
  secret: 51cb758772bdc07674d3ab291a05bda6e84d0d63ad69cf13844c12a3c4fb0ffc
  expiration: 25200000 # 先设置为半分钟 方便进行调试
  refreshExpiration: 25200000

avatar:
  avatarPath: "data/avatar/default.jpg"

